-- The canonical, secure schema is versioned in:
-- supabase/migrations/20260915165812_secure_auth.sql
-- Apply that complete migration in Supabase SQL Editor as the database owner.
-- See docs/AUTHENTICATION.md for rollout, Auth settings, and admin provisioning.
-- This file intentionally contains no permissive legacy policy definitions.
